config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'comments/create'
  get 'comments/edit'
  get 'comments/update'
  get 'comments/destroy'
  resources :posts
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'home#index'
  get 'home/index'
  devise_scope :user do # rutas dentro de una cuenta
    get '/posts', to: 'posts#index', as: 'posts_index'
    get '/posts/new', to: 'posts#new', as: 'new_posts'
    post '/posts', to: 'posts#create', as:'posts_create'
    get '/posts/:id', to: 'posts#show', as: 'post_show'
    put '/posts/:id', to: 'posts#update'
    put '/posts/:id/edit', to: 'posts#edit', as: 'editing_post'
    delete '/posts/:id', to: 'posts#destroy'
    delete '/comments/:id', to: 'comments#destroy'

    get '/posts/:post_id/solicits', to:          'solicits#index', as: 'solicits'
    delete '/posts/:post_id/solicits/:solicit_id', to: 'solicits#destroy', as: 'delete_solicit'
    post '/posts/:post_id/solicits/:solicit_id/aceptar', to: 'solicits#aceptar', as: 'aceptar_solicit'
    post '/posts/:post_id/solicits/:solicit_id/rechazar', to: 'solicits#rechazar', as: 'rechazar_solicit'

    post   '/posts/:post_id/solicits', to:         'solicits#create', as: 'create_solicit'
    get    '/posts/:post_id/solicits/new', to:     'solicits#new', as: 'new_solicit'
    patch  '/posts/:post_id/solicits/:id', to: 'solicits#update'
  end
  resources :posts do
    resources :comments
  end
  resources :posts do
    resources :comments, only: [:create]
  end
  
  resources :conversations do
    resources :messages
  end
  
  get '/calendar/:post_id', to: 'calendars#index', as: 'calendar'

  get '/perfil', to: 'home#perfil', as: 'perfil'
  delete '/conversations/:conversation_id/messages/:id', to: 'messages#destroy', as: 'destroy_message'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:perfil]
  def index; end

  def perfil
    @user = current_user
    @posts = @user.posts
    # Renderizar la vista de perfil
    render 'perfil'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Página de inicio</title>
  <!-- Agrega tus enlaces de estilos CSS y scripts JS aquí -->
</head>
<body>
  <!-- Encabezado -->
  <header>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <!-- Contenido del encabezado, como el logotipo y el menú de navegación -->
  </header>

  <!-- Contenido principal -->
  <main>
    <nav class="navbar">
        <div class="container">
          <div id="navMenu" class="navbar-menu">
            <div class="navbar-start">
              <%= link_to "Clases particulares", posts_index_path , class:"navbar-item"%>
                
              </a>
            </div>

            <div class="navbar-end">
              <div class="navbar-item">
                <div class="buttons">
                    <span class="navbar-item">
                        <% if user_signed_in? %>
                            <%= button_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "button is-dark" %>
                        <% else %>
                            <%= link_to "Iniciar Sesión", new_user_session_path, class: "button is-dark" %>
                        <% end %>
                    </span>
                    <span class="navbar-item">
                        <% if user_signed_in? %>
                            <%= link_to "Mi Perfil", perfil_path, class: "button is-primary" %>
                        <% else %>
                            <%= link_to "Registrarse", new_user_registration_path, class:"button is-primary" %>
                        <% end %>
                    </span>
                  
                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>

      <section class="hero is-primary is-fullheight-with-navbar">
        <iframe src="https://javimujicab.github.io/Test/" width="100%" height="3490"></iframe>
      </section>
    <!-- Otro contenido principal de la página de inicio -->
  </main>

  <!-- Pie de página -->
  <footer>
    <!-- Contenido del pie de página, como enlaces de contacto y derechos de autor -->
  </footer>

  <!-- Agrega tus scripts JS al final del cuerpo de la página -->
</body>
</html>

app/views/home/perfil.html.erb




<div class="container-fluid" style="height: 100vh; display: flex; padding: 0;">
    <div class="column is-one-quarter" style=" display: flex; background-color: #00D1B1;">


        <div class="tile is-parent is-vertical">
            <article class="tile is-child notification is-primary" style="height: 100%; width: 100%;">
                <div class="content has-text-centered" style="display: flex; flex-direction: column; justify-content: center;">

                    <figure class="image is-256x256">
                    
                        <%= image_tag("icono3.png", alt: "Descripción de la imagen") %>



                    </figure>
                    <section class="section"></section>
                    <div class="field is-grouped">
                        <div class="control">
                            <%= link_to "Crear Publicación", new_post_path, class: "button is-primary" %>
                        </div>
                    </div>
                    <div class="field is-grouped">
                        <div class="control">
                            <%= link_to "Todas las Publicaciones", posts_path, class: "button is-primary" %>
                        </div>
                    </div>
                    <div class="field is-grouped">
                        <div class="control">
                            <%= link_to "Editar perfil", edit_user_registration_path, class: "button is-primary" %>
                        </div>
                    </div>
                    <div class="field is-grouped">
                        <div class="control">
                            <%= link_to "Mensajes", conversations_path, class: "button is-primary" %>
                        </div>
                    </div>
                    <div class="field is-grouped">
                        <div class="control">
                            <%= button_to "Solicitudes enviadas", solicits_path(0), method: :get, class: "button is-primary"%>
                        </div>
                    </div>
                    <div class="field is-grouped">
                        <div class="control">
                            <%= link_to "Home",root_path, class: "button is-primary"%>
                        </div>
                    </div>
                    <div class="field is-grouped">
                        <div class="control">
                            <%= button_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "button is-primary is-inverted" %>
                        </div>
                    </div>


                </div>
            </article>
        </div>

    </div>
    <div class="column" style=" display: flex ; background-color: #f2f2f2; flex-direction: column;">
        <div class="sub-container" style="flex: 1; background-color: #f2f2f2; margin-bottom: 20px; display: flex; align-items: center; ">
            <h2 class="title is-2 has-text-left" style="margin-right: 10px; font-weight: 400; color: #00D1B1;">Bienvenid@ <%= @user.name %></h2>
        </div>
        <div class="sub-container" style="flex: 1; background-color: #f2f2f2; margin-bottom: 20px;">
            <h2 class="title is-4 has-text-left" style="margin-left: 10px; font-weight: 600;">Mis Publicaciones</h2>
            <% @posts.each_slice(3) do |post_group| %>
                <div class="tile is-child">
                    <div class="columns is-multiline">
                    <% post_group.each do |post| %>
                        <div class="column is-one-third">
                        <%= render partial: post, locals: { page: 'perfil' } %>
                        </div>
                    <% end %>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="sub-container" style="flex: 1; background-color: #f2f2f2;"></div>
    </div>
    <!-- Contenido del contenedor a la derecha del mosaico aquí -->
  </div>
</div>