config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'comments/create'
  get 'comments/edit'
  get 'comments/update'
  get 'comments/destroy'
  resources :posts
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                     path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'home#index'
  get 'home/index'
  devise_scope :user do # rutas dentro de una cuenta
    get '/posts', to: 'posts#index', as: 'posts_index'
    get '/posts/new', to: 'posts#new', as: 'new_posts'
    post '/posts', to: 'posts#create', as:'posts_create'
    get '/posts/:id', to: 'posts#show', as: 'post_show'
    put '/posts/:id', to: 'posts#update'
    put '/posts/:id/edit', to: 'posts#edit', as: 'editing_post'
    delete '/posts/:id', to: 'posts#destroy'
    delete '/comments/:id', to: 'comments#destroy'

    get '/posts/:post_id/solicits', to:          'solicits#index', as: 'solicits'
    delete '/posts/:post_id/solicits/:solicit_id', to: 'solicits#destroy', as: 'delete_solicit'
    post '/posts/:post_id/solicits/:solicit_id/aceptar', to: 'solicits#aceptar', as: 'aceptar_solicit'
    post '/posts/:post_id/solicits/:solicit_id/rechazar', to: 'solicits#rechazar', as: 'rechazar_solicit'

    post   '/posts/:post_id/solicits', to:         'solicits#create', as: 'create_solicit'
    get    '/posts/:post_id/solicits/new', to:     'solicits#new', as: 'new_solicit'
    patch  '/posts/:post_id/solicits/:id', to: 'solicits#update'
  end
  resources :posts do
    resources :comments
  end
  resources :posts do
    resources :comments, only: [:create]
  end
  
  resources :conversations do
    resources :messages
  end
  
  get '/calendar/:post_id', to: 'calendars#index', as: 'calendar'

  get '/perfil', to: 'home#perfil', as: 'perfil'
  delete '/conversations/:conversation_id/messages/:id', to: 'messages#destroy', as: 'destroy_message'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :solicits, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :titulo, presence: { message: 'El título es obligatorio' }
  validates :sigla_ramo, presence: { message: 'La sigla del ramo es obligatoria' }
  validates :precio, presence: { message: 'El precio es obligatorio' }
  validates_numericality_of :precio, message: "Debe ser un número"
  validates :descripcion, presence: { message: 'La descripción es obligatoria' }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    filtro_categoria = params[:filtro_categoria]

    if filtro_categoria && filtro_categoria != '-'
      @posts = Post.where(categoria: filtro_categoria)
    else
      @posts = Post.all
    end

    @filtrado = (filtro_categoria != '-' && filtro_categoria)
    @filtrado = filtro_categoria
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    # pass @post to the view
    render :show, locals: { post: @post }
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }

      else
        format.html { render :new, status: :unprocessable_entity }

      end
    end
  end

  def update
    respond_to do |format|
      @post = Post.find(params[:id])
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }

      else
        format.html { render :edit, status: :unprocessable_entity }

      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:titulo, :sigla_ramo, :precio, :descripcion, :user_id, :categoria) # ##obsssss
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<style>
  body {
    background-color: rgba(0, 209, 177,0.3); /* Color primario con transparencia */
  }
</style>

<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> -> no podemos guardar tu post :( </h2>

      <ul>
        <% post.errors.each do |error| %>
         <li><%= error.message %></li>

        <% end %>
      </ul>
    </div>
  <% end %>


  <body>
      <section class="hero is-fullheight">
        <div class="hero-body">

          <div class="container is-max-desktop is-centered "style="max-width: 600px; ">
            <div class="notification is-white">

              <label class="label has-text-primary is-size-3" style="font-weight: 600;">Crear Publicación</label>

              <div>
                <p class="title is-4"><%= form.label :Título, style: "display: block" %></p>
                <%= form.text_field :titulo, class: "input is-primary is-small is-hovered", autofocus: true, placeholder: "De qué se tratarán las clases?" %>
              </div>
              <br>
              <div>
                <p class="subtitle"><%= form.label :Sigla_del_ramo, style: "display: block" %></p>
                <%= form.text_field :sigla_ramo, class: "input is-primary is-small is-hovered", autofocus: true, placeholder: "Qué ramo enseñarás?" %>
              </div>
              <br>
              <div>
                <p class="subtitle is-6"><%= form.label :Precio, style: "display: block" %></p>
                <%= form.text_field :precio, class: "input is-primary is-small is-hovered", autofocus: true, placeholder: "$$$" %>
              </div>
              <br>
              <div>
                <p class="subtitle is-6"><%= form.label :Descripción, style: "display: block" %></p>
                <%= form.text_area :descripcion, class: "textarea is-primary", placeholder: "Explica cómo son tus clases y cómo puedes ayudar a tus alumnos" %>
              </div>
              <br>
              <div>
                <p class="subtitle is-6"><%= form.label :Categoría, style: "display: block" %></p>
                <%= form.select :categoria, ["Matemáticas", "Programación", "Física", "Química", "Biología", "Economía", "Lenguaje", "Deportes","Otro"], :required => true %>
              </div>
              <br>


              <div class="buttons" style="display: flex; justify-content: flex-end;">

                <a href="<%= perfil_path %>" class="button">Volver atrás</a>
                <div class="actions">
                  <%= form.submit "Crear",class: "button is-primary"%>
                </div>

              </div>



          </div>
        </div>
      </div>
    </section>
  </body>
<% end %>

app/views/posts/_post.html.erb

  <% if page == 'index' %>
    <div id="<%= dom_id post %>">
      <div class="tile is-parent">
        <article class="tile is-child box">
          <div class="columns">
            <div class="column is-two-thirds">
              <p class="title"><%= post.titulo %></p>
              <p class="subtitle"><%= post.sigla_ramo %></p>
              <table class="table is-hoverable">

                <tbody>
                  <tr>
                    <td>Precio</td>
                    <td><%= post.precio %></td>

                  </tr>
                  <tr>
                    <td>Descripción</td>
                    <td><%= post.descripcion %></td>

                  </tr>
                  <tr>
                    <td>Profe</td>
                    <td><%= post.user.name %></td>

                  </tr>
                  <tr>
                    <td>Categoría</td>
                    <td><%= post.categoria %></td>

                  </tr>

                </tbody>
              </table>
            </div>
            <div class="column ">


            </div>
          </div>
          <% if user_signed_in? %>
            <div class="buttons is-centered">

              <button class="button is-primary is-focused is-pulled-left is-inverted" 
              onclick="window.location.href='<%= post_path(post) %>'">Ver publicación</button>

              <% if post.user != current_user%>
                <%= button_to "Solicitar clase", new_solicit_path(post_id: post.id), method: :get, class: "button is-primary is-focused is-pulled-left" %>
              <% end %>
            </div>
          <% end %>

        </article>

      </div>
    </div>

  <% elsif page == 'perfil' %>
    <div id="<%= dom_id post %>">
      <div class="tile is-parent">
        <article class="tile is-child box">
          <p class="title"><%= post.titulo %></p>
          <p class="subtitle"><%= post.sigla_ramo %></p>
          <table class="table is-hoverable">

            <tbody>
              <tr>
                <td>Precio</td>
                <td><%= post.precio %></td>

              </tr>
              <tr>
                <td>Descripción</td>
                <td><%= post.descripcion %></td>

              </tr>
              <tr>
                <td>Profe</td>
                <td><%= post.user.name %></td>

              </tr>
              <tr>
                <td>Categoría</td>
                <td><%= post.categoria %></td>

              </tr>

            </tbody>
          </table>
          <button class="button is-primary is-focused is-pulled-right is-inverted" 
          onclick="window.location.href='<%= post_path(post) %>'">Ver publicación</button>
        </article>
      </div>
    </div>

  <% else %>
    <br>
    <div id="<%= dom_id post %>" class="columns is-gapless is-multiline is-fullheight">
      <div class="container is-fullheight is-fullwidth">
        <div class="container is-parent is-fullheight">
          <article class="container is-child box is-fullheight ">
            <p class="title is-2"><%= post.titulo %></p>
            <p class="subtitle is-3"><%= post.sigla_ramo %></p>
            <table class="table is-hoverable">

              <tbody>
                <tr>
                  <td>Precio</td>
                  <td><%= post.precio %></td>

                </tr>
                <tr>
                  <td>Descripción</td>
                  <td><%= post.descripcion %></td>

                </tr>
                <tr>
                  <td>Profe</td>
                  <td><%= post.user.name %></td>

                </tr>
                <tr>
                  <td>Categoría</td>
                  <td><%= post.categoria %></td>

                </tr>

              </tbody>
            </table>
          <div>
            <%= button_to "Disponibilidad de horas", calendar_path(post_id: @post.id), method: :get, 
            class: "button is-primary" %>
          </div>
          </article>

  
          

          <article class="container is-child box">

            <p class="title has-text-weight-light">Comentarios</p>
            <p class="subtitle">Revisa las reseñas de tus compañeros o coméntanos como te fue con la clase!</p>
            <% if user_signed_in? %>
              <p>
                  <%= render post.comments %>
                  <%= render partial: 'comments/form', locals: { post: post } %>

              </p>

            <% end %>

          </article>


        </div>
      </div>
    </div>
  <% end %>



app/views/posts/edit.html.erb
<h1>Editar post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Ver detalles", @post %> |
  <%= link_to "Volver a los posts", posts_path %>
</div>

app/views/posts/index.html.erb
<style>
  body {
    background-color: rgba(242, 242, 242,0.4); /* Color primario con transparencia */
    height: 300vh; /* Establece la altura del body al 100% de la ventana del navegador */
    margin: 0;
  }
  .custom-select {
  appearance: none;
  background-color: white;
  border: 1px solid #ccc;
  padding: 10px 12px;
  border-radius: 4px;
  font-size: 14px;
  width: 200px;
}

.custom-select:focus {
  outline: none;
  box-shadow: 0 0 4px #aaa;
}
.center-container {
  display: flex;
  justify-content: center;
}


</style>



<section class="hero is-primary is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">

          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <a href="<%= root_path %>" class="navbar-item">
              Home
            </a>
            <% if  user_signed_in?%>
              <a href="<%= new_post_path %>" class="navbar-item">
              Crear publicación
              </a>
              <a href="<%= conversations_path %>" class="navbar-item">
              Mensajes
              </a>

            <%end%>
            <% unless user_signed_in?%>
              <a href="<%= new_user_session_path %>"class="navbar-item">
                Iniciar Sesión
              </a>
              <a href="<%=new_user_registration_path%>"class="navbar-item">
                Sign up
              </a>
            <% end %>
            <span class="navbar-item">
              <a href="<%=perfil_path%>" class="button is-primary is-inverted">
                <span class="icon">
                  <i class="fab fa-github"></i>
                </span>
                <span>Mi Perfil</span>
              </a>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        Clases para todos
      </p>
      <p class="subtitle">
        Encuentra tu study buddy para cualquier ramo
      </p>
    </div>
  </div>

  <!-- Hero footer: will stick at the bottom -->
  <div class="hero-foot">

  </div>
</section>


<div class="center-container" style="margin-top: 20px;">
  <%= form_for "", url: posts_url, method: :get do |f| %>
    <div class="field is-grouped">
      <div class="control custom-icon-margin">
        <span class="icon is-small is-left" style="margin-top: 15px;">
          <i class="fas fa-search" aria-hidden="true"></i>
        </span>
      </div>
      <div class="control">
        <%= f.select :filtro_categoria, ["-", "Matemáticas", "Programación", "Física", "Química", "Biología", "Economía", "Lenguaje", "Deportes", "Otro"], { selected: @filtro_categoria }, { class: "custom-select" } %>
      </div>
      <div class="control">
        <%= f.submit "Filtrar", class: "button is-primary is-focused is-inverted" %>
      </div>
    </div>
  <% end %>
</div>




<div class="tile is-ancestor">
  <div class="tile is-parent is-vertical">
    <% @posts.each_slice(3) do |post_group| %>
      <div class="tile is-child">
        <div class="columns is-multiline">
          <% post_group.each do |post| %>
            <div class="column is-one-third">
              <%= render partial: post, locals: { page: 'index' } %>

            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<style>
  body {
    background-color: rgba(242, 242, 242,0.4); /* Color primario con transparencia */
    height: 250vh; /* Establece la altura del body al 100% de la ventana del navegador */
    margin: 0;
  }
</style>



<section class="hero is-primary is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">

          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <a href="<%=posts_index_path%>" class="navbar-item ">
              <span>Todas las Publicaciones</span>
            </a>
            <a href="<%=perfil_path%>" class="navbar-item ">
              <span>Mi Perfil</span>
            </a>
            <a href="<%= root_path %>" class="navbar-item is-active">
              Home
            </a>

          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        Clases para todos
      </p>
      <p class="subtitle">
        Encuentra tu study buddy para cualquier ramo
      </p>
    </div>
  </div>

  <!-- Hero footer: will stick at the bottom -->
  <div class="hero-foot">

  </div>
</section>


<%= render partial: post, locals: { page: 'detallado' } %>

<div>

  <% if user_signed_in? && current_user == @post.user %>
    <article class="container is-child box">
      <p class="title has-text-weight-light">Solicitudes recibidas</p>
      <p class="subtitle">Acepta o rechaza las solicitudes que han hecho de tu clase</p>


        <p>
        <table class="table is-hoverable">

          <tbody>
            <tr>
              <th>Nombre</th>
              <th>Fecha</th>
              <th>Mensaje</th>
              <th>Estado</th>


            </tr>
            <% @post.solicits.each do |solicit| %>
              <tr>
                <td><%= solicit.user.name %></td>
                <td><%= solicit.fecha%></td>
                <td><%= solicit.mensaje %></td>
                <td><%= solicit.aceptado %></td>
                <% if solicit.aceptado == 'pendiente'%>
                  <td><%= button_to "Aceptar", aceptar_solicit_path(solicit_id: solicit.id, post_id: post.id), class: "link"%></td>
                  <td><%= button_to "Rechazar", rechazar_solicit_path(solicit_id: solicit.id, post_id: post.id), class: "link"%></td>
                <% end %>
              </tr>
            <% end %>


          </tbody>
        </table>



        </p>



    </article>
    <br>
    <div class="buttons is-centered">

      <button class="button is-primary is-focused is-pulled-left is-inverted" 
      onclick="window.location.href='<%= editing_post_path(@post) %>'">Editar publicación</button>
      <%= button_to "Borrar publicación", @post, 
      method: :delete, class: "button is-primary is-focused is-pulled-left" %>

    </div>


  <% end %>
  <div class="container">
    <div class="is-flex justify-end">
      <% if user_signed_in? && current_user != @post.user %>
        <%= form_with(url: conversations_path, method: :post) do |form| %>
          <%= form.hidden_field :sender_id, value: current_user.id %>
          <%= form.hidden_field :recipient_id, value: @post.user.id %>
          <%= form.submit "Enviar mensaje a #{@post.user.name}", class: "button is-primary" %>
          
        <% end %>
        <br>
        
      <% end %>
    </div>
    <br>
    <% if user_signed_in? && current_user != @post.user %>
      <%= button_to "Solicitar clase", new_solicit_path(post_id: @post.id), method: :get, class: "button is-primary is-focused is-pulled-left is-inverted" %>
    <% end %>
 </div>
  
    <%#= link_to "Enviar mensaje a #{@post.user.name}", conversations_path(sender_id: current_user.id, recipient_id:
    @post.user.id), method: 'post', class:"button is-link"%>
  <%# else %>
    <%# link_to "Conversations", conversations_path %>
  <%# end %>
</div>


</div>